id: IDFD8384D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:16:15+00:00'
last_modified: '2022-06-08T10:11:45.876389+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3425
  title: བོད་ཀྱི་བརྡ་སྤྲོད་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A9C6:
      image_group_id: I3CN7751
      title: ''
      total_pages: 268
      order: 1
      base_file: A9C6.txt
    547A:
      image_group_id: I3CN7752
      title: ''
      total_pages: 0
      order: 2
      base_file: 547A.txt
    AD24:
      image_group_id: I3CN7753
      title: ''
      total_pages: 0
      order: 3
      base_file: AD24.txt
    1F7D:
      image_group_id: I3CN7754
      title: ''
      total_pages: 0
      order: 4
      base_file: 1F7D.txt
    '8956':
      image_group_id: I3CN7755
      title: ''
      total_pages: 0
      order: 5
      base_file: 8956.txt
    EE5B:
      image_group_id: I3CN7756
      title: ''
      total_pages: 0
      order: 6
      base_file: EE5B.txt
    AB72:
      image_group_id: I3CN7757
      title: ''
      total_pages: 0
      order: 7
      base_file: AB72.txt
    FB27:
      image_group_id: I3CN7758
      title: ''
      total_pages: 0
      order: 8
      base_file: FB27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
