id: P009322
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:20.853934
source_metadata:
  id: bdr:W3CN3425
  title: བོད་ཀྱི་བརྡ་སྤྲོད་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    8b3ff0f4cedc46edafdb4999e89a8b9e:
      image_group_id: I3CN7751
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
    452caa4de4514be7a842c80610b1c627:
      image_group_id: I3CN7752
      title: ''
      volume_number: 2
      total_pages: 0
    de99cded7c554aeebd39270411f83024:
      image_group_id: I3CN7753
      title: ''
      volume_number: 3
      total_pages: 0
    7aecd2d9bd9441f8bf021fcc9137ec16:
      image_group_id: I3CN7754
      title: ''
      volume_number: 4
      total_pages: 0
    1e068a27eba245d194362ff89f2f7c0a:
      image_group_id: I3CN7755
      title: ''
      volume_number: 5
      total_pages: 0
    dcb24011c26c49f3a96bdc47624d406e:
      image_group_id: I3CN7756
      title: ''
      volume_number: 6
      total_pages: 0
    131dc4585c9b43c4b0df34155cdf3f82:
      image_group_id: I3CN7757
      title: ''
      volume_number: 7
      total_pages: 0
    4cbd914ac4944120a575a4b674bbcb7a:
      image_group_id: I3CN7758
      title: ''
      volume_number: 8
      total_pages: 0
    0899a97f82be4c4f9ec46dc03eebd524:
      image_group_id: I3CN7759
      title: ''
      volume_number: 9
      total_pages: 0
    ac5a5bf9e3774402b136827ea82e29cf:
      image_group_id: I3CN7760
      title: ''
      volume_number: 10
      total_pages: 310
      base_file: v002.txt
    897f9fe34e724bed9aff15efd7ccf985:
      image_group_id: I3CN7761
      title: ''
      volume_number: 11
      total_pages: 356
      base_file: v003.txt
    3ae5ddc8c83549fcafa3e4c0906a6483:
      image_group_id: I3CN7762
      title: ''
      volume_number: 12
      total_pages: 414
      base_file: v004.txt
    0ca256414f7244118bb9b197c7bd892e:
      image_group_id: I3CN7763
      title: ''
      volume_number: 13
      total_pages: 488
      base_file: v005.txt
    2cca521d41a647419bbd31ca679c6d9a:
      image_group_id: I3CN7764
      title: ''
      volume_number: 14
      total_pages: 480
      base_file: v006.txt
    f22082d357bb4571b33c49d043fcfee3:
      image_group_id: I3CN7765
      title: ''
      volume_number: 15
      total_pages: 388
      base_file: v007.txt
    d774a0a56801410ea6982bc3d23c31a3:
      image_group_id: I3CN7766
      title: ''
      volume_number: 16
      total_pages: 115
      base_file: v008.txt
    5c97424e10554ef0898d4a305a419e8d:
      image_group_id: I3CN7767
      title: ''
      volume_number: 17
      total_pages: 0
    b08710897e5a4ec9954e14030900a996:
      image_group_id: I3CN7768
      title: ''
      volume_number: 18
      total_pages: 0
    2b41adc5ef664899927d06e5383bdd04:
      image_group_id: I3CN7769
      title: ''
      volume_number: 19
      total_pages: 0
    e834d12eccd34686958979eae549ae2c:
      image_group_id: I3CN7770
      title: ''
      volume_number: 20
      total_pages: 0
    32215d55ce9e4ce9aec22adb3fd66c5f:
      image_group_id: I3CN7771
      title: ''
      volume_number: 21
      total_pages: 0
    4a8bc99fdbf04b0c90032180e6fb29d7:
      image_group_id: I3CN7772
      title: ''
      volume_number: 22
      total_pages: 0
    204a8ff242394330b66bd04e3a0aa2cf:
      image_group_id: I3CN7773
      title: ''
      volume_number: 23
      total_pages: 0
    088d93eb63db4dbdbba4c0d5759a335f:
      image_group_id: I3CN7774
      title: ''
      volume_number: 24
      total_pages: 0
    cfd3dd17a89e46d483f788a0cbc0dadc:
      image_group_id: I3CN7775
      title: ''
      volume_number: 25
      total_pages: 0
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
